stages: 
  - init                 # * To add engagement ot Deffect Dojo
  - secrets-scan            # * To add secrets analysis
  - code-scan            # * To add code analysis and SonarQube steps
  - image-scan           # * To add dependencies check step
  - dast                 # * To add DAST analyser
  - sec-mobile           # * To add Mobsf security scan
  - subdomains-detect    # * To add infrastructure security scan
  - subdomains-scan      # * To add infrastructure security scan


# All scan stages should wait for defectdojo preparation stage
.needs_init:
  needs: 
    - job: init
      artifacts: true

# Of course it should have allow_failure by default
.allow_failure:
  allow_failure: true

# Runner tags. Dev repositories should have access to them
.tags:
  tags:
    - hc

.image:
  image: $CI_REGISTRY/whitespots/devsecops/security-images/toolset:latest
include:
  
  # Scaner versions + defectdojo url
  - local: '.gitlab/variables.yml'
    ref: 'dev'
  
  # DefectDojo preparation stage
  - local: '.gitlab/init.yml'
    ref: 'dev'

  # Scan stages
  - local: '.gitlab/secrets-scan.yml'
    ref: 'dev'
  - local: '.gitlab/code-scan.yml'
    ref: 'dev'
  - local: '.gitlab/image-scan.yml'
    ref: 'dev'
  - local: '.gitlab/dast.yml'
    ref: 'dev'
  - local: '.gitlab/sec-mobile.yml'
    ref: 'dev'
  - local: '.gitlab/sonarqube.yml'
    ref: 'dev'
  - local: '.gitlab/infrastructure.yml'
    ref: 'dev'

  # Upload report stage
  - local: '.gitlab/templates/.after-script-dd-upload-report.yml'
    ref: 'dev'



